name: Create Release Artifacts
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, macos-13, ubuntu-latest]
        include:
          - os: macos-latest
            TARGET: aarch64-apple-darwin
            ARTIFACT_NAME: bookmark-darwin-aarch64
          - os: macos-13
            TARGET: x86_64-apple-darwin
            ARTIFACT_NAME: bookmark-darwin-x86_64
          - os: ubuntu-latest
            TARGET: x86_64-unknown-linux-gnu
            ARTIFACT_NAME: bookmark-linux-amd64
    steps:
      - uses: actions/checkout@v1
      - run: echo ${{matrix.TARGET}}
      - name: Build Artifacts
        run: cargo build --verbose --release --target ${{matrix.TARGET}}
      - name: Rename Artifacts
        run: mv ./target/${{matrix.TARGET}}/release/bookmark ${{matrix.ARTIFACT_NAME}}
      - name: Upload Release Asset
        id: upload-release-asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            bookmark-darwin-aarch64
            bookmark-darwin-x86_64
            bookmark-linux-amd64
